### ISSUE TITLE
[Feature] Redirect to a different CDN 

### ISSUE THREAD

**Issue by trickypr** [wesaphzt/block-all-google#1]
I was wondering if it would be possible to instead of blocking things like google apis, if you could redirect them to a different CDN with the same content. This could quite well be impossible but it’s worth asking.

**Comment by wesaphzt** [comment]
Thanks for the suggestion, apologies for not seeing it earlier.
To be honest with you I wouldn't even know where to start with this.
It's probably possible but it's a bit out of scope for the aim of this script, which is just a blanket block of Google.
That said, it's open to change and improvements if anyone wants to have a 'bash' at it. But it's probably beyond my capabilities to implement something like this.
I'll leave the issue open.
